services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    FourPaws\CatalogBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Tests,Dto,Collection}'

    FourPaws\CatalogBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    FourPaws\CatalogBundle\ParamConverter\:
        resource: '../../ParamConverter/*'
        tags: ['request.param_converter']

    # Используется в компонентах (@todo private)
    FourPaws\CatalogBundle\Service\DiscountMarkService:
        public: true

    # Постараться спрятать за интерфейс
    # @see
    FourPaws\CatalogBundle\Service\FilterService:
        public: true

    FourPaws\CatalogBundle\Service\FilterHelper:
        class: FourPaws\CatalogBundle\Service\FilterHelper
        arguments: ['@bx.hlblock.filter']
        public: true

    FourPaws\CatalogBundle\Service\OftenSeekRepository:
        class: FourPaws\CatalogBundle\Service\OftenSeekRepository
        public: true