security:
  providers:
    bitrix:
      id: FourPaws\UserBundle\Security\BitrixUserProvider
  firewalls:
    api:
      pattern: ^/api/
      stateless: true
      api_token: true
    main:
      anonymous: ~
      logout: ~
      guard:
        authenticators:
          - FourPaws\UserBundle\Security\BitrixAuthenticator
  access_control:
    - { path: ^/api/start, roles: ROLE_NO_TOKEN }
    - { path: ^/api/fake, roles: ROLE_NO_TOKEN }
    - { path: ^/api(?!/start|?!/fake), roles: ROLE_API }