services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    FourPaws\DeliveryBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Tests,EventController,Dpd,Repository}'

    FourPaws\DeliveryBundle\Command\DpdLocationsImport:
        class: FourPaws\DeliveryBundle\Command\DpdLocationsImport
        arguments:
          - null
          - host: '%dpd.ftp.host%'
            port: '%dpd.ftp.port%'
            login: '%dpd.ftp.login%'
            password: '%dpd.ftp.password%'
            directory: '%dpd.ftp.directory%'
            filemask: '%dpd.ftp.filemask%'
            localpath: '%dpd.ftp.localpath%'

    delivery.service:
        class: FourPaws\DeliveryBundle\Service\DeliveryService
        public: true

    FourPaws\DeliveryBundle\Service\IntervalService:
        class: FourPaws\DeliveryBundle\Service\IntervalService
        public: true

    FourPaws\DeliveryBundle\Service\DpdLocationService:
        class: FourPaws\DeliveryBundle\Service\DpdLocationService
        public: true

