services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    FourPaws\SaleBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Tests,EventController,Payment}'

    FourPaws\SaleBundle\Service\BasketService:
        class: FourPaws\SaleBundle\Service\BasketService
        public: true

    FourPaws\SaleBundle\Service\BasketViewService:
        public: true
        arguments: ['@FourPaws\SaleBundle\Service\BasketService']

    FourPaws\SaleBundle\Service\NotificationService:
        class: FourPaws\SaleBundle\Service\NotificationService
        public: true

    FourPaws\SaleBundle\Service\OrderService:
        class: FourPaws\SaleBundle\Service\OrderService
        public: true

    FourPaws\SaleBundle\Service\OrderPropertyService:
        class: FourPaws\SaleBundle\Service\OrderPropertyService
        public: true

    FourPaws\SaleBundle\Service\OrderStorageService:
        class: FourPaws\SaleBundle\Service\OrderStorageService
        public: true

    FourPaws\SaleBundle\Service\PaymentService:
        class: FourPaws\SaleBundle\Service\PaymentService
        public: true

    FourPaws\SaleBundle\Service\UserAccountService:
        class: FourPaws\SaleBundle\Service\UserAccountService
        public: true

    FourPaws\SaleBundle\Discount\Manzana:
        class: FourPaws\SaleBundle\Discount\Manzana
        public: true
