---

user:
    resource: '@FourPawsUserBundle/AjaxController'
    type: annotation
    prefix: '/user'

sale:
    resource: '@FourPawsSaleBundle/AjaxController'
    type: annotation
    prefix: '/sale'

catalog:
    resource: "@FourPawsCatalogBundle/AjaxController"
    type: annotation
    prefix: '/catalog'

delivery:
    resource: '@FourPawsDeliveryBundle/AjaxController'
    type: annotation
    prefix: '/delivery'

store:
    resource: '@FourPawsStoreBundle/AjaxController'
    type: annotation
    prefix: '/store'

personal:
    resource: '@FourPawsPersonalBundle/AjaxController'
    type: annotation
    prefix: '/personal'

location:
    resource: "@FourPawsLocationBundle/AjaxController"
    type: annotation
    prefix: '/location'

food.selection:
    resource: '@FourPawsFoodSelectionBundle/AjaxController'
    type: annotation
    prefix: '/food_selection'


autosort.property.hint:
  path: /autosort/property-hint/{propertyId}
  defaults: { _controller: '\FourPaws\ProductAutoSort\Controller\AutosortController::propertyHint' }
  methods: [GET]
  requirements:
    propertyId: '\d+'

comments.add:
  path: /comments/add/
  defaults: { _controller: '\FourPaws\AppBundle\AjaxController\CommentsController::addAction' }
  methods: [POST]

comments.catalog.add:
  path: /comments/catalog/add/
  defaults: { _controller: '\FourPaws\AppBundle\AjaxController\CommentsController::addByCatalogAction' }
  methods: [POST]

comments.next:
  path: /comments/next/
  defaults: { _controller: '\FourPaws\AppBundle\AjaxController\CommentsController::nextAction' }
  methods: [GET]

form.feedback:
  path: /form/feedback/add/
  defaults: { _controller: '\FourPaws\Form\AjaxController\FeedBackController::addAction' }
  methods: [POST]

form.callback:
  path: /form/callback/add/
  defaults: { _controller: '\FourPaws\Form\AjaxController\CallBackController::addAction' }
  methods: [POST]

form.faq:
  path: /form/faq/add/
  defaults: { _controller: '\FourPaws\Form\AjaxController\FaqController::addAction' }
  methods: [POST]
