---

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

ajax.routes:
    resource: "ajax.yml"
    prefix:   /ajax
    condition: "request.isXmlHttpRequest()"

app.catalog:
    resource: "@FourPawsCatalogBundle/Controller/"
    type: annotation

app.api:
    resource: "@FourPawsMobileApiBundle/Resources/config/routing.yml"

old_items.news:
    path: /actions_and_programs/news/{path}/
    defaults: { _controller: '\FourPaws\AppBundle\Controller\OldPublicationController::oldNewsDetailAction' }
    methods: [GET]

old_items.articles:
    path: /actions_and_programs/article/{path}/
    defaults: { _controller: '\FourPaws\AppBundle\Controller\OldPublicationController::oldArticleDetailAction' }
    methods: [GET]

old_items.sale:
    path: /actions_and_programs/{path}/
    defaults: { _controller: '\FourPaws\AppBundle\Controller\OldPublicationController::oldSaleDetailAction' }
    methods: [GET]
