services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    FourPaws\PersonalBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Tests}'

    address.service:
        class: FourPaws\PersonalBundle\Service\AddressService
        public: true

    pet.service:
        class: FourPaws\PersonalBundle\Service\PetService
        public: true

    referral.service:
        class: FourPaws\PersonalBundle\Service\ReferralService
        public: true

    bonus.service:
        class: FourPaws\PersonalBundle\Service\BonusService
        public: true

    order.service:
        class: FourPaws\PersonalBundle\Service\OrderService
        public: true

    order_subscribe.service:
        class: FourPaws\PersonalBundle\Service\OrderSubscribeService
        public: true

    FourPaws\PersonalBundle\AjaxController\:
        resource: '../../AjaxController'
        public: true
        tags: ['controller.service_arguments']

